	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, BROWN, GRAY, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, RED, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, RED, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, BROWN, ROOF, ROOF
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN, TEXT
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN